#!/bin/sh
. ./sharr.sh

images_glob='./test/resources/*.jpg'

i=0
for image in ${images_glob}
do
	# shellcheck disable=SC2086
	prev_image="$(arr_prev "$i" ${images_glob})" && previous="<a href='${prev_image}'>previous</a>"
  # shellcheck disable=SC2086
	next_image="$(arr_next "$i" ${images_glob})" && next="<a href='${next_image}'>next</a>"

	cat > ${image%.jpg}.html <<- ----
		<h1>$(basename ${image})</h1>
		<img src='${image}' />

		${previous}
		${next}
----
	: "$((i=i+1))"
done